### ISSUE TITLE
create a manifest.json file and add a basic layout of an webextension 

### ISSUE THREAD

**Issue by Ajitesh13** [HakinCodes/extension-activity-logger#2]
To claim this bug, you need to specify what is your planned folder structure and explain, why you have planned like that

**Comment by devanshiv123** [comment]
@Ajitesh13  I want to take up this issue. According to me folder structure should be :  

Activity-logger/
      icons/
      content_scripts/
          script.js

      manifest.json

Here, Activity-logger is the main directory under which we have to create manifest.json directly. content_script will contain the file that will tell the the Firefox to load the script to do the task. icons will contain images that will be shown in Add-ons section.

**Comment by Ajitesh13** [comment]
@devanshiv123 It looks fine, but there's lot of scope of improvements. To get assigned to this issue, you need to create a PR specifying the contents of `manifest.json` file

**Comment by deprov447** [comment]
I have some iteration regarding this:

**Main folder/**
-- manifest.json
-- popup.html
-- Options.html
-- License
-- **icons/**
-- **scripts/** 
---------background.js
---------options.js
---------popup.js
-- **styles/**
---------popup.css
---------options.css

**Comment by Ajitesh13** [comment]
@deprov447 Please explain your folder structure, why you have thought like this ? What is popup.html ? What is options.html ? And to get assigned to this issue create a PR in which create a `manifest.json` file and fill its expected contents

**Comment by deprov447** [comment]
@Ajitesh13 okay,
**popup.html** is the the small html doc which will open on clicking the extension icon.
**options.html** is the browser interface for configuring extension
**background.js** is main process logging the activity of other extensions

**Comment by deprov447** [comment]
@Ajitesh13 Please review the PR made #6
